#!/bin/bash
# ███╗   ███╗ █████╗ ████████╗████████╗███████╗      
# ████╗ ████║██╔══██╗╚══██╔══╝╚══██╔══╝██╔════╝      
# ██╔████╔██║███████║   ██║      ██║   ███████╗      
# ██║╚██╔╝██║██╔══██║   ██║      ██║   ╚════██║      
# ██║ ╚═╝ ██║██║  ██║   ██║      ██║   ███████║      
# ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝      ╚═╝   ╚══════╝      
                                                   
#  █████╗ ██╗     ██╗ █████╗ ███████╗███████╗███████╗
# ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
# ███████║██║     ██║███████║███████╗█████╗  ███████╗
# ██╔══██║██║     ██║██╔══██║╚════██║██╔══╝  ╚════██║
# ██║  ██║███████╗██║██║  ██║███████║███████╗███████║
# ╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
# 

###########################################                              
## NOTES
##
## Make sure that the following command is in the ~/.bashrc file (replace PATH with the path to this file): "source PATH"
###########################################

###########################################                              
# VARIABLES
###########################################                                 
# Location of scripts directory
scriptsDir=""

# Location of this file
thisFile="/home/$USER/.bash_aliases"

# Location of .vimrc
vimrc="/home/$USER/.vimrc"

###########################################                                 
# SETUP .VIMRC
###########################################
echo "\"This file is automatically generated when the aliases are reloaded." > $vimrc
echo "\"Make changes to $thisFile." >> $vimrc
echo "colorscheme desert" >> $vimrc
echo "set number" >> $vimrc
echo "set tabstop=2" >> $vimrc
echo "set softtabstop=0 noexpandtab" >> $vimrc
echo "set shiftwidth=2" >> $vimrc
echo "set autoindent" >> $vimrc
echo "set smartindent" >> $vimrc
echo "set mouse=a" >> $vimrc

###########################################                                 
# ALIASES FILE ALIASES
###########################################  

# Edits the this file and reloads it on exit
alias editalias="vim $thisFile; source $thisFile"

# Reloads this file
alias reloadalias="source $thisFile"

# Prints the contents of this file to the console
alias calias="cat $thisFile"

###########################################                                 
# BASIC ALIASES
###########################################

# Edit the .vimrc file (Changes will be temporary)
alias editvim="vim $vimrc"

# ls lists all files with color
alias ls="ls -a --color=auto"

# ll list all files with perms with color
alias ll="ls -la --color=auto"

# vi opens vim
alias vi="vim"

# Clears the console
alias cls="clear"

# su is sudo su
alias su="sudo su"

# Prints the storage utilization in a human readable form
alias space="df -h"

# Prints the size of the passed directory or the size of the currrent directory if nothing is passed
alias size="du -sh"

###########################################                                 
# CHANGE DIRECTORIES
###########################################

# Navigates to the scripts directory
alias scripts="cd $scriptsDir"

# Navigates up one directory
alias ..="cd .."

# Navigates to /
alias root="cd /"

###########################################                                 
# TMUX COMMANDS
###########################################

# Create a new tmux session
alias newtmux="tmux new -s"

# Lists all of the tmux sessions
alias tmuxs="tmux ls"

# Attaches to the passed tmux session
alias tmuxa="tmux a -t"
